### ISSUE TITLE
Same label text overwrites different size labels

### ISSUE THREAD

**Issue by nseidle** [sparkfunX/Buzzard#18]
To duplicate:

run makelabel "GND"

![image](https://user-images.githubusercontent.com/117102/92625857-6ad36600-f286-11ea-8632-b47583232942.png)

This will generate a label in default size.

run makelabel -s 0.08 "GND"

![image](https://user-images.githubusercontent.com/117102/92625892-73c43780-f286-11ea-861d-f47bb1260ec8.png)

This will generate a larger label. As soon as the larger label is generated, the original label is replaced/increased in size by the current GND text.

Both labels have the Footprint "GND0" from library "output" so I can see why Eagle is getting confused. It would be nice to add a partial hash to the end of each footprint name when it's generated to make it unique from similar text.

**Comment by oclyke** [comment]
@nseidle i think this issue aligns with the general concept I was talking about in #17. perhaps we could use a hash of all the settings for a given entry as a unique identifier in the footprint name. however then changing settings would *not* update existing labels on-board which can of course be a desired effect.

two conflicting ideas:
- link labels so that they can be automatically updated on-board with Eagle
- create separation between label names to avoid unintentional overwrites

i'd love to tackle this but it will be some time before i can get back around to it

**Comment by NPoole** [comment]
I talked to Pete Lewis about this for a while the other day and we decided that for now, it's as much a feature as it is a bug. I'm going to close this for now but keep it in mind going forward. 

@oclyke if you have a brain blast about solving this, feel free to open another issue and I'll work on it.
